### ISSUE TITLE
Is there a way to save the desktop?

### ISSUE THREAD

**Issue by nowislewis** [Vidianos-Giannitsis/zetteldesk.el#9]
I saw zetteldesk could save the node content into a scratch buffer, and then users can save the buffer into a file. But if users want to continue edit these nodes, the scratch buffer couldn’t be updated.

I wonder if there is a way to save the desktop(only the node index or tag index, so it’s a dynamic filter) and reload it later. So users can continue work on this desktop until they feel good enough for all the related nodes. This is much convenient that users can quickly recover the topic. And this maybe a zetteldesk alternative for another good package org-ql.

Thank you for your great work, zetteldesk has a smart idea about notes.

**Comment by Vidianos-Giannitsis** [comment]
Hi, thanks for your kind words.

The ability to save the desktop was actually on my wishlist for the original MELPA release. However, due to not having so much time at that point and not really having any idea of how this could be implemented I just left it.

But, since my exams end tomorrow, I will definitely have a lot more time now so perhaps its time to revisit this as I fully agree it would be useful. If you, or anyone else who might perhaps stumble upon this issue has a clue on how to do this, I would love to hear. I will also try to do some more research myself and hopefully I will find the solution.

**Comment by Vidianos-Giannitsis** [comment]
[The latest commit](https://github.com/Vidianos-Giannitsis/zetteldesk.el/commit/99c5434a809da0b783f31b10872c8cb2a2176e2d) I made solves this issue. Check the functions `zetteldesk-save-state` and `zetteldesk-restore-desktop` for this functionality. Will be writing more documentation on this feature in the next few days but time's out for the day. At least all the functions are documented though.

**Comment by nowislewis** [comment]
You did a great job, thank you
